### ISSUE TITLE
Configurable "Mail Service"

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#109]
Implement a configurable service that sends e-mails whose body is defined as a Freemarker template.

**Comment by ildave** [comment]
I have implemented the requirement (#eaac758) in a very basic way due to lack of specification details.

**Comment by xeviscc** [comment]
@ildave You can check the following github project in order to have an idea of how to integrate templates: https://github.com/jhipster/jhipster-sample-app-nocache/blob/master/src/main/java/com/mycompany/myapp/service/MailService.java

I hope it helps.

**Comment by guidospadotto-profesia** [comment]
@gioppoluca we would like you to further refine the requirement, as it was created as a feature request from you. Thanks! :)

**Comment by gioppoluca** [comment]
Ok here some more info:
1) we need to have an additional column in the service table where we place the template reference
2) decide if the template get placed in jackrabbit or in DB (maybe jackrabbit is better, but I leave it to you)
3) add the template addition during the process of adding a new service.

---------
During service subscription we need to:
1)  get the template fill it with the data
2) create the mail and send it

Also to define:
1) placeholders in the mail that is how to write in the template stuff like SUBSCRIBER_NAME SERVICE_NAME etc and write some doc for it so that we know that placeholder1=variable1 etc

To do this we need to (requirements for other pieces):
1) have as "required" the mail of the subscriber (I think is already like this but check it out)

**Comment by xeviscc** [comment]
* In my opinion I will go for saving the template in jackrabbit.
* A default template should be offered.
* Agree with create a document with guidelines on how to do a template should be provided.

**Comment by guidospadotto-profesia** [comment]
For the sake of speed, please provide the "base/default" Freemarker template (otherwise Davide will have to study FreeMarker in addition to JackRabbit, Spring Boot and all else). The publisher will take care of providing his own.

**Comment by xeviscc** [comment]
Here you have an example: http://javaquicknotes.com/questionDelegator/FreeMarker_Email_Template

Hope it helps

**Comment by gioppoluca** [comment]
I will take care of the default template and the parameter and variable substitution part

**Comment by ildave** [comment]
I cannot find any documentation about the data model, so I am not able to decide the right place to add the column to store the jackrabbit path for the email template.
Should I add it to the Customization entity?

**Comment by xeviscc** [comment]
You should discuss that with Teamnet. Try to contact @cpopsa, @pdaniel or @ciprianpavel

**Comment by ciprianpavel** [comment]
As @gioppoluca said earlier it must be on service level not on customization level. So the correct entity is "application"
