### ISSUE TITLE
Check permissions on each query, not only screens

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#123]
We have to be sure that each query is executed for the proper user, and that one user cannot access to the data from another one.

**Comment by cpopsa** [comment]
Can you provide more details about this? Which are the queries and the data specific to a certain user?

**Comment by xeviscc** [comment]
In the front-end we already try to manage security by providing only the allowed endpoint to the user, but a malintentioned user could try to check urls called and change it to retrieve information from another one or all of them.

**Comment by xeviscc** [comment]
The specific data could be:
* Subscribed services (customizations)
* Owned services.
* Personal data
* Belonging to an organization.
* Clouds accounts.

**Comment by gioppoluca** [comment]
we need to remember that when a user is active in the system he can see just its own data and the one of the organization he is in unless he is an admin.
That is the normal way of working of any system, we need to be sure we enforce this so if I log with a service provider I need to see the list of services that belongs to me for example, same for all entities that have relations with user or organization.

**Comment by cpopsa** [comment]
So a READ operation in genearal should behave like this:
- a user with ROLE_ADMIN can read all the info from DB, other users can read only info that is related to the organization to which they belong.
For example, a user with ROLE_ADMIN can visualize all the applications, but a regular user can read only the applications belonging to user organization.

What about create/update/delete operations?
What type of user can create/update/delete Organizations, Applications, Customizations, CloudAccounts ?

**Comment by gioppoluca** [comment]
In general each user can operate only on its organization data apart the admin that can operate on all and some entities that behave differently:
- CloudAccounts needs to be written by organization users but can be red either by ID directly (the orchestrator will issue a query without bothering who is running the system since we already did the check in the proper time, or if the service allows for a try before you buy the subscriber could choose between its own cloud_accounts or the one that the SP has defined as the trial one.
In general what you stated is true all actors see and write their own stuff

**Comment by gioppoluca** [comment]
Organization can be added just by admin or (in the pending state) as autoregistration (do not know which user is running in htat moment, but there could be none

**Comment by gioppoluca** [comment]
Applications are added just by organization's users so if user1 belong to org1 all the application he create shoiuld be by default of org1 and he can edit, delete etc just org1 stuff, than we could implement an admin role for users in the organization, but at the moment is enough to have it working in the proper way

**Comment by gioppoluca** [comment]
customization are created by subscribers and service providers and admin.
Since creating a customization is the business of the project all can do it.
Again obviously each see only customization in the following way:
subscriber: see just cust of its org
service provide: see all cust related to its org's applications
admin see all

**Comment by cpopsa** [comment]
Done. I also updated spring boot to latest version (1.3.2.RELEASE) and solved migration issues, because I needed some features that were not available in previous version (1.2.8.RELEASE).

**Comment by cpopsa** [comment]
@PreAuthorize is a annotation from spring security which allows or denies method execution based on the value of an expression.

Example 1 (OrganizationService.java):
	@PreAuthorize("hasRole('ROLE_ADMIN') or (principal.organizationId == #organizationId)")
	Organizations findOneAndInitCloudAccountCollection(Long organizationId);
	
The method will be executed if the current user has role 'ROLE_ADMIN' or his organization is the same as organizationId method param. Otherwise an "Access is denied" exception will be thrown.

Example 2 (OrganizationService.java):
	@PreAuthorize("hasRole('ROLE_ADMIN') or (#organizationDTO.organizationStatus.id == T(eu.cloudopting.domain.util.OrganizationStatusEnum).Pending.id)")
	Organizations create(OrganizationDTO organizationDTO);
	
The method will be executed if the current user has role 'ROLE_ADMIN' or the newly organization to be created is in the pending state. Otherwise an "Access is denied" exception will be thrown.


Example 3 (ToscaService.java):
	@PreAuthorize("hasRole('ROLE_ADMIN') or @toscaAuthorization.hasReadCustomizationPermission(#idApp)")
	public JSONObject getCustomizationFormData(Long idApp, String csarPath) {

		return customizationUtils.getCustomizationFormData(idApp, csarPath);

	}
	
The method will be executed if the current user has role 'ROLE_ADMIN' or method hasReadCustomizationPermission from ToscaAuthorizationImpl.java returns true. Otherwise an "Access is denied" exception will be thrown.
