### ISSUE TITLE
The DB customizations table should have a constraint for status_id

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#165]
Where do we have to check the status of the customization table in the database? Could it be linked to the corresponding table?

**Comment by gioppoluca** [comment]
yes we need a separate status table for all the entities so that when we need to show combo etc we know perfectly what to look for OR add a column to the status table and specify that status to which entity refer @cpopsa your decision as it fit you best [I believe that a separate table is better also for managing it but ...]

**Comment by cpopsa** [comment]
I created a new table - customization_status and a foreign key from status_id to customization_status. The Java code is also updated.
