### ISSUE TITLE
We should have an script to recreate the database in any moment.

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#201]
We should have an script to recreate the database in any moment.
This script should have the structure of the database and the minimum data to allow the platform run.
It should be maintained.

**Comment by xeviscc** [comment]
The issue is assigned to @cpopsa, but it has to be updated for anyone that modifies something in the database.

**Comment by xeviscc** [comment]
Firs script created: https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/postgres_cloudopting_database_initial_script.sql

**Comment by cpopsa** [comment]
In order to keep track of database modifications I configured Flyway.
All db modifications (ddl and dml also) should be placed in .sql files at location database-component\src\main\resources\db\migration.
The sql files will be executed in db when application starts, there is no need for other configuration, params etc. You can find out info about executed scripts in schema_version table.

The naming convention for sql files is as follows:

V<VERSION>__<DESCRIPTION>.sql
<VERSION> - script version. Needs to be higher than previous one.
<DESCRIPTION> - short description of operations contained in the file.

The file https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/postgres_cloudopting_database_initial_script.sql is not needed anymore, should be deleted.

**Comment by guidospadotto-profesia** [comment]
I think it would be better to have Flyway automatically generate (and NOT apply) the aggregation of scripts in a single DDL file. I do not know if this is possible.

**Comment by xeviscc** [comment]
At the moment it is ok for me.

**Comment by xeviscc** [comment]
According to @cpopsa we will need a script to create the database and Flyway will take care of all the objects inside.

**Comment by cpopsa** [comment]
Execution of script https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/postgres_cloudopting_database_initial_script.sql fails with:
ERROR: insert or update on table "monitoring_info_elastic" violates foreign key constraint "fk_monelastic_customization"
  Detail: Key (customization_id)=(4067) is not present in table "customizations".

**Comment by xeviscc** [comment]
This script has been replaced for https://github.com/CloudOpting/deploy-cloudopting/blob/master/database/files/initial_script.sql
