### ISSUE TITLE
Category of services

### ISSUE THREAD

**Issue by ciprianpavel** [CloudOpting/cloudopting-manager#271]
What is the purpose of the category of services?
Are these categories managed in the system or are hardcoded in UI only?

Either remove them from UI or implement them properly.

**Comment by genismauri** [comment]
Why instead of deleting this was not fixed it?

**Comment by xeviscc** [comment]
We could not fix something that was not work because it wasn't a requirement. 
It was introduced by the design people without knowing if we will use it or not.
This enhancement can be done, but is not as trivial as it may seem. 
Changes starts from the UI, but it has to change the way the applications get published, we have to change the database, ...
If you think it should be there we can create an issue in order to implement it in the future.

**Comment by genismauri** [comment]
Understood, thanks! I guess then an issue should be opened for further releases.

This can be a bad question from the reviewers: "You talk about offering vertical solutions, how can I see that implemented in the Catalogue?"

**Comment by xeviscc** [comment]
I guess it should.
This issue is closed, so better to write this down in the correct place for not losing it.
