### ISSUE TITLE
Problems with the size of the images for the services in the home page

### ISSUE THREAD

**Issue by genismauri** [CloudOpting/cloudopting-manager#317]
The ones from Wordline are pretty good, but most of the others are not adjusted to the frame.
There should be a predetermined format/size.

**Comment by xeviscc** [comment]
The size of the "window" is 358px x 258px, so it should be de size if the intention is to make images fit exactly as they are. Now a "style" called **cover** is applied in order to have the full width and height occupied.

It can be changed to **contain** in order to see the catalogue like following screenshot:

![image](https://cloud.githubusercontent.com/assets/10829055/14286496/83d4e09e-fb4f-11e5-820c-a160942722c5.png)

**Comment by xeviscc** [comment]
Images with the correct size or proportion should be uploaded.
