### ISSUE TITLE
TOSCA IDE - Add default Virtual Host

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#359]
The Virtual host is mandatory, so it should be placed always as a default component.

**Comment by gioppoluca** [comment]
On the Apache node?
Not true.
Apache can have a default VH but it can also NOT have it and in this case you need to provide the proper VH with the node ApacheVH.
Unless there are better requests this can be closed.

**Comment by xeviscc** [comment]
Not the Apache node, but the first node. The Virtual Host (Virtual Machine) before Docker Containers, Apache, Tomcat, etc...

**Comment by gioppoluca** [comment]
Ah ... now I understand.
We are lazy :D

**Comment by xeviscc** [comment]
Yes, we have to work for the end user. We have to assume the end user does not know anything.

**Comment by gioppoluca** [comment]
Unfortunately the end user NEED to know something.
Plus the problem we have is that we load dynamically the list that is both the array and json list and all this can change in time (also the content or the name) I have nothing to understand that VHost is the first mandatory node since I have no attributes apart the name that could be changed and depend on the XML content.
I do not like to "hard code" a "add VHost" code so in the manual the user will be instructed to add a VHost node as the first operation. Than if he wants he can save a JSON file as a starting point and be happy with that.
