### ISSUE TITLE
TOSCA IDE - Add an explanation of each field in "node data"

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#366]
Each node needs its own fields that have to be filled in a certain way. If CloudOpting has to keep increasing its size and number of nodes this can get even more complicated.

Each field should have a little explanation of what it is and how it should be filled.

**Comment by xeviscc** [comment]
We may try to put a help box with an explanation. The same for #367.

**Comment by gioppoluca** [comment]
This is not practical.
Unless we manage to find a way to create hover box text over the fields (and is a bit difficult since the library we are using does not have that feature).
Beyond there will be the problem of translation since is not possible to translate that part due to the fact that all the text come dynamically from XML and there is no language file for it
