### ISSUE TITLE
TOSCA IDE - Add warnings in case of errors

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#367]
At the moment the TOSCA IDE does not warn you about errors or bugs you have done while using it and you have to check manually the TOSCA file. 

This means that however uses the TOSCA IDE it will need an expertise with TOSCA and that if the error is not found the person will be working with the wrong files until it discovers they do not work.

We need the TOSCA IDE being able to detecf the most common or possible errors and warn the person using them.

**Comment by xeviscc** [comment]
We cannot validate all data inserted by the user. The user has to know what he/she is doing.

**Comment by MiquelBonetSDG** [comment]
May be not all data can be inserted but if you know that in a certain field it should go something like "%%USERINPUT%%" and it says "%USERINPUT%%". The TOSCA IDE should warn you that there is an error in node "XXX" and field "YYY".

This way, you will be sure that at least there are not stupid mistakes like this ones.

**Comment by xeviscc** [comment]
We will put the information on how it work, but will not put warning for each input box.

**Comment by gioppoluca** [comment]
At the moment having the IDE is already a big help.
Producing a proper doc for using it properly is fundamental, but is not possible to check for errors since the complexity of the things that could be written is enormous.
You need to consider that the IDE generate dynamically things without knowing what they are it just allows you to write things and at the moment we manage to force you to properly write boolean, choose between options etc. where this is possible.
All the rest is care and checking the results.
