### ISSUE TITLE
Problem building images

### ISSUE THREAD

**Issue by j-fuentes** [CloudOpting/cloudopting-manager#37]
It seems that something in the process is still wrong:

1- CO-Manager request CO-Crane to create a new Context and waits until it is created. __GOOD__
2- After context ready, CO-Manager requests CO-Crane to build a new image (the first) and wait until it is created. __GOOD__
3- CO-Manager must do the previous step for each image, but It finishes the first one and goes to step 1 (in a infinite loop).  __BAD__

There are also some exceptions in certain queries to the database. Maybe the problem is related to that.

Execution log: http://pastebin.com/fSvxUyc4

**Comment by gioppoluca** [comment]
Please check if the docker build executes correctly in the crane environment it seems that there are errors in the build process.
in the meantime I check the other parts of the code
Luca

**Comment by gioppoluca** [comment]
The problem is in the call to the DockerService.isBuild method
after a fewcalls it break and does not work anymore this generate something I have not jet intercepted that causes the process to start again.
Maybe the task fails so this causes the reload
Can you check what happens on a call to the isBuild and activate some logging on crane debug will be easier

**Comment by j-fuentes** [comment]
Something makes crane erase his datastore. I am making some changes to avoid that.

**Comment by j-fuentes** [comment]
The new version I am testing right now solves the problem in the datastore. It will be released early next week.

**Comment by j-fuentes** [comment]
Solved in https://github.com/CloudOpting/cloudopting-crane/releases/tag/0.8
