### ISSUE TITLE
Service Catalogue - Contact confirmation message is too short

### ISSUE THREAD

**Issue by MiquelBonetSDG** [CloudOpting/cloudopting-manager#394]
When you contact CloudOpting through the contact form, the message received is too short and lacks explanation. 

Instead of:

"Dear */Name/*,
Message:
*/ Message sent to CloudOpting/*
has been sent."

It should be:

"Dear (Name),

We have received the following message, with ID (ID of the message), from you:

_(Message sent to CloudOpting)_

We will get back to you with an answer as soon as possible.

Kind regards,

**CloudOpting Team**"

**Comment by ildave** [comment]
I made the change, but I cannot test it locally because the captcha is not working when running the application from localhost and the "Send message" button is not enabled:

![schermata 2016-08-12 alle 16 27 57](https://cloud.githubusercontent.com/assets/3855605/17625582/ca35ba26-60a9-11e6-8d06-8c7ed735ff90.png)

**Comment by xeviscc** [comment]
Added localhost and dev.cloudopting.org to the list of allowed domains for our recaptcha key.

**Comment by ildave** [comment]
Closed - commit 39923f7214b1bd863108496012b67f9616d0df49
