### ISSUE TITLE
Problems sending emails from a Docker container

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#50]
The cloudopting-manager sends mails for registration purposes, and seems that the mails sent inside a Docker container does not work.

@j-fuentes Could you please check it, please?

**Comment by j-fuentes** [comment]
The problem is not related with the container.

I tried in and outside a container and the application is doing the same.

I tried to register a new user with a mail with domain 'wtelecom.es' and it doesn't work (reading the log, it says the email address is not valid). I tried also with a gmail account and it sends the mail correctly (and the log says that the address is correct).

It is necessary to check the code in the mail service. Maybe there is a method that parses the email and it is not prepared for '.es' domains or something.

**Comment by xeviscc** [comment]
Seems that the server choosen was not the correct one.

[Google Apps SMTP settings to send mail from a printer, scanner, or app - Google Apps Administrator Help](https://support.google.com/a/answer/176600?hl=en)

Could you try with this configuration:
Server: smtp.gmail.com
Port: 465

**Comment by xeviscc** [comment]
@j-fuentes Could you test it again in a Docker container? I have made some changes in the Gmail account and also in the code itself.

**Comment by j-fuentes** [comment]
It works!
