### ISSUE TITLE
Organisation/Users Management UI

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#66]
We need a UI to manage organisations and their associated users, with assignable roles.
(This issue is used only as a reminder and as a way of getting notifications once implementation is available)
@xeviscc @gioppoluca

**Comment by xeviscc** [comment]
A first version with the basic functionalities of the managmenent was pushed. 
Waiting for some changes on the REST API in order to continue with the front-end.
Dependencies: 
* Endpoints to edit cloud accounts #65
* Change request body: Endpoint POST and PUT /api/users #64
* Endpoints "GET /api/users" and "GET /api/users/{idUser}" should return its roles #63

**Comment by xeviscc** [comment]
CRUD screens for User/Organization Management have been created.

* Users Management:
![image](https://cloud.githubusercontent.com/assets/10829055/12546672/a48da46a-c34b-11e5-9096-6c7b0db3cecd.png)

* Organizations Management:
![image](https://cloud.githubusercontent.com/assets/10829055/12546689/bec01138-c34b-11e5-922a-6af01faf192a.png)
