### ISSUE TITLE
Error on executing Mongo docker-compose generated by the orchestrator

### ISSUE THREAD

**Issue by xeviscc** [CloudOpting/cloudopting-manager#84]
I am facing problems on executing the docker-compose done by the orchestrator:

```console
debian@debian:/cloudOptingData/csi-MongoC4C$ docker-compose -f docker-compose.yml up
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'MongoC4C_DC' configuration key 'volumes' '0' contains an invalid type, it should be a string
Service 'MongoC4C_DC' configuration key 'ports' value ['27017:27017', '27017:27017'] has non-unique elements
```

In the docker-compose.yml we can see that the ports are duplicated, and if no volumes are defined it appears with an empty value that makes it fail:

```yml
MongoC4C_DC:
  image: cloudopting/csi_mongoc4c_dc


  ports:
   - "27017:27017"
   - "27017:27017"
  log_driver: "fluentd"
  log_opt:
    fluentd-address: "84.240.187.4:4044"
    labels: eu.cloudopting.log 


  volumes:
    - 
MongoC4C_DC:
  image: cloudopting/csi_mongoc4c_dc


  ports:
   - "27017:27017"
   - "27017:27017"
  log_driver: "fluentd"
  log_opt:
    fluentd-address: "84.240.187.4:4044"
    labels: eu.cloudopting.log 


  volumes:
    - 
```

**Comment by gioppoluca** [comment]
For the duplicated ports you need to check the file if you have the info duplicated.
For volumes the thing is tricky:
 in the IDE the angularjs-form component create an empty array even if we do not write anything in the array fields.
So for volumes we need to "remove" the array element in the IDE so that the property will be considered null and not empty.
Doing this (and you have to do it each time you save the "docker" node) in the XML and the orchestrator you correctly find no volumes and the checks see that there are no elements..

Let me know on the ports if there is something in your TOSCA duplicated or there could be a real bug in the orchestrator (never occurred to me)

**Comment by xeviscc** [comment]
Close it because it is old. I will reopen it if the error persists.
